### ISSUE TITLE
Error creating new site with advanced template

### ISSUE THREAD

**Issue by carbinemonoxide** [zurb/foundation-sites-6#228]
I am getting an error when trying to create a new foundation project using the advanced template:

Downloading the project template.../usr/local/lib/node_modules/foundation-cli/node_modules/graceful-fs/polyfills.js:14
  chdir.call(process, d)
        ^

Error: ENOENT: no such file or directory, uv_chdir
    at Error (native)
    at process.chdir (/usr/local/lib/node_modules/foundation-cli/node_modules/graceful-fs/polyfills.js:14:9)
    at process.chdir (/usr/local/lib/node_modules/foundation-cli/node_modules/bower/node_modules/bower-config/node_modules/graceful-fs/polyfills.js:18:9)
    at process.chdir (/usr/local/lib/node_modules/foundation-cli/node_modules/bower/node_modules/graceful-fs/polyfills.js:14:9)
    at process.chdir (/usr/local/lib/node_modules/foundation-cli/node_modules/npm/node_modules/graceful-fs/polyfills.js:18:9)
    at /usr/local/lib/node_modules/foundation-cli/lib/commands/new.js:84:15
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/foundation-cli/node_modules/exec/exec.js:90:5)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)

This is happening with a fresh install of node and foundation-cli@beta

**Comment by CGTS** [comment]
I am getting this same error.
Windows 10
npm:  3.4.0
node: 4.2.2

**Comment by joepurdy** [comment]
If I had to take a guess I'd say this is an issue with the v4.x.x branch of node and npm v3.x.x

I encountered the same error using node 4.2.0 and npm 3.3.6. I used nvm to install node v0.12.7 and npm v2.11.3 and the foundation new command from foundation-cli@2.0.0-beta.2 worked for installing the advanced template for foundation 6.

**Comment by gakimball** [comment]
@joepurdy I fixed a typo in the `new` command that was preventing advanced templates from installing, which I believe will fix this issue.

@carbinemonoxide Can you run `npm install foundation-cli@beta --global` to update to a newer version of the CLI, and try the command again?

**Comment by carbinemonoxide** [comment]
@gakimball After completely uninstalling foundation-cli and reinstalling it using the command given, I still get the same error:

carbine@Poseidon ~                                                                                                                                                        [18:00:57]
> $ foundation -v                                                                                                                                                           ⬡ 5.0.0
Foundation CLI version 2.0.0-beta

carbine@Poseidon ~                                                                                                                                                        [18:01:03]
> $ foundation new                                                                                                                                                          ⬡ 5.0.0
? What are you building today? A website (Foundation for Sites)
? What's the project called? test.project
? Which template would you like to use? Advanced: includes a static site generator, and Sass/JS compilers

            .
           /|     ,
      , /|/  \/| /|       Thanks for using ZURB Foundation for Sites!
     /|/       |/ |       -------------------------------------------
 |___|            |___|   Let's set up a new project.
 \___|  ^^   ^^   |___/   It shouldn't take more than a minute.
     | -[O]--[O]- |
     |    ___,    |
     |    ...     |
      \__________/


Downloading the project template.../usr/local/lib/node_modules/foundation-cli/node_modules/graceful-fs/polyfills.js:14
  chdir.call(process, d)
        ^

Error: ENOENT: no such file or directory, uv_chdir
    at Error (native)
    at process.chdir (/usr/local/lib/node_modules/foundation-cli/node_modules/graceful-fs/polyfills.js:14:9)
    at process.chdir (/usr/local/lib/node_modules/foundation-cli/node_modules/bower/node_modules/bower-config/node_modules/graceful-fs/polyfills.js:18:9)
    at process.chdir (/usr/local/lib/node_modules/foundation-cli/node_modules/bower/node_modules/graceful-fs/polyfills.js:14:9)
    at process.chdir (/usr/local/lib/node_modules/foundation-cli/node_modules/npm/node_modules/graceful-fs/polyfills.js:18:9)
    at /usr/local/lib/node_modules/foundation-cli/lib/commands/new.js:84:15
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/foundation-cli/node_modules/exec/exec.js:90:5)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)

**Comment by gakimball** [comment]
Hm, try using this explicit version: `npm install foundation-cli@2.0.0-beta.2`. If it still doesn't work then, it's a different issue.

**Comment by carbinemonoxide** [comment]
@gakimball Works great. Thanks!

**Comment by gakimball** [comment]
@carbinemonoxide Awesome! :)

**Comment by gBaylaender** [comment]
I have the same problem with the version 2.3.2, to resolve I downgraded my foundation-cli to the version 2.0.0.

Window 10
Node: 6.11.2
npm: 5.4.0


![2017-08-30_09h34_55](https://user-images.githubusercontent.com/1658712/29861641-2caec6c8-8d6a-11e7-83ac-f4eea6c1589c.png)
