### ISSUE TITLE
Menu Style "Flash" on Load

### ISSUE THREAD

**Issue by JeremyEnglert** [zurb/foundation-sites-6#276]
Since many of the menu classes are injected with JS, the menu sometimes remains unstyled for a few moments while all of the files load. The most noticeable issue being with dropdown menus being displayed briefly.

Would it make sense to initially set these items to be hidden with CSS and then have that changed via JS when the classes are added? However, accessibility would have to be considered here as well.

**Comment by gakimball** [comment]
In Foundation 5 we used `.no-js` here and there for no-JavaScript fallbacks. If we add that in, maybe we can have some temporary style overrides for menus before they're fully-rendered.

**Comment by zurbchris** [comment]
This seems like a good idea. The flash is pretty obnoxious, and there's a lot that has to be processed before they can be rendered properly. Maybe one simple solution would be to set the display of `.is-*-submenu` to none or visibility hidden.

**Comment by gakimball** [comment]
@zurbchris Can you add something to Foundation's `init()` method that removes `.no-js` from `<html>`? Our templates have the class pre-added, so that will allow me to do this fallback stuff.

**Comment by gakimball** [comment]
Fixed with [this commit](https://github.com/zurb/foundation-sites/commit/63f024250a77627214621ebd45a8c31b7f46cbfa).

**Comment by JeremyEnglert** [comment]
@gakimball I just downloaded the newest version and I'm still seeing a "flash". I double checked and .no-js & ul is in the Sass file.

![k4lrc1q24b](https://cloud.githubusercontent.com/assets/6110968/11433930/d9e91ec6-9481-11e5-995c-fb4e2fb5ea43.gif)
